const ACTION_TYPE = {
  SET_SONG_OBJECT_IN_LIST: 'SET_SONG_OBJECT_IN_LIST',
  SET_CURRENT_SONG_OBJECT: 'SET_CURRENT_SONG_OBJECT',
  SET_SCREEN: 'SET_SCREEN',
  DEZEER_ERROR: 'DEZEER_ERROR',
  RESET_DEZEER_ERROR: 'RESET_DEZEER_ERROR',
  SET_GAME_RESULT: 'SET_GAME_RESULT',
  SET_CURRENT_TRY: 'SET_CURRENT_TRY',
  SET_CURRENT_ROUND: 'SET_CURRENT_ROUND',
};

export const SCREENS = {
  MAIN_SCREEN: 'MAIN_SCREEN',
  SONG_SCREEN: 'SONG_SCREEN',
  RESULT_SCREEN: 'RESULT_SCREEN',
};

export default ACTION_TYPE;
