const ACTION_TYPE = {
  SET_SONG_OBJECT_IN_LIST: 'SET_SONG_OBJECT_IN_LIST',
  SET_CURRENT_SONG_OBJECT: 'SET_CURRENT_SONG_OBJECT',
  SET_SCREEN: 'SET_SCREEN',
  // SET_USER_SCRO
};

export default ACTION_TYPE;
